// eslint-disable-next-line import/no-anonymous-default-export
export default {
  services: [
    {
      'id':1,
      'name':'Fabricación y venta de saunas unipersonales',
      'price':'',
      'breve': 'Somos fabricantes de saunas unipersonales hecho en Perú',
      'buttontype':'Comprar',
      'tipo':'producto',
      'linkbtn':"fabricación-y-venta",
      'mensaje':'Hola%20buenas%20tardes%20deseo%20adquirir%20un%20sauna%20unipersonal%2C%20por%20favor%20indicarme%20el%20costo%20y%20medio%20de%20pago..',
      'imagen':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/1.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/2.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/3.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/4.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/5.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/6.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/7.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/8.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/9.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/10.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/11.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/12.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/13.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/14.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/15.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/16.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/17.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/18.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/19.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/1/20.jpg"
        },
      ]
    },
    {
      'id':2,
      'name':'Reparaciones y Mantenimiento',
      'price':'',
      'breve': 'Hacemos reparaciones y mantenimientos en fibra de vidrio a domicilio',
      'buttontype':'solicitar',
      'tipo':'servicios',
      'linkbtn':"reparaciones-y-mantenimiento",
      'mensaje':'Hola%20buenas%20tardes%20deseo%20adquirir%20el%20servicio%20de%20Reparaciones%20y%20Mantenimiento%20en%20fibra%20de%20vidrio%2C%20como%20es%20el%20prodecimiento...',
      'imagen':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/1/1.jpg"
        },
        {
          'id':2,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/1/2.jpg"
        },
        {
          'id':3,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/1/3.jpg"
        },
        {
          'id':4,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/1/4.jpg"
        },
        {
          'id':5,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/1/5.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/1/6.jpg"
        },
        {
          'id':7,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/1/7.jpg"
        },
        {
          'id':8,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/1/8.jpg"
        },
        {
          'id':9,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/1/9.jpg"
        },
        {
          'id':10,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/1/10.jpg"
        },
      ],
      'imagentwo':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/2/1.jpg"
        },
        {
          'id':2,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/2/2.jpg"
        },
        {
          'id':3,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/2/3.jpg"
        },
        {
          'id':4,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/2/4.jpg"
        },
        {
          'id':5,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/2/5.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/2/6.jpg"
        },
        {
          'id':7,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/2/7.jpg"
        },
        {
          'id':8,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/2/8.jpg"
        },
        {
          'id':9,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/2/9.jpg"
        },
        {
          'id':10,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/2/10.jpg"
        },
      ],
      'imagenthree':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/3/1.jpg"
        },
        {
          'id':2,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/3/2.jpg"
        },
        {
          'id':3,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/3/3.jpg"
        },
        {
          'id':4,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/3/4.jpg"
        },
        {
          'id':5,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/3/5.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/3/6.jpg"
        },

      ],
      'imagenfour':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/4/1.jpg"
        },
        {
          'id':2,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/4/2.jpg"
        },
        {
          'id':3,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/4/3.jpg"
        },
        {
          'id':4,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/4/4.jpg"
        },
        {
          'id':5,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/4/5.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/4/6.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/4/7.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/4/8.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/4/9.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/4/10.jpg"
        },

      ],
      'imagenfive':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/5/1.jpg"
        },
        {
          'id':2,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/5/2.jpg"
        },
        {
          'id':3,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/5/3.jpg"
        },
        {
          'id':4,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/5/4.jpg"
        },
        {
          'id':5,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/5/5.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/5/6.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/5/7.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/5/8.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/5/9.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/5/10.jpg"
        },

      ],
      'imagensix':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/6/1.jpg"
        },
        {
          'id':2,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/6/2.jpg"
        },
        {
          'id':3,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/6/3.jpg"
        },
        {
          'id':4,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/6/4.jpg"
        },
        {
          'id':5,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/6/5.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/6/6.jpg"
        },

      ],
      'imagenseven':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/7/1.jpg"
        },
        {
          'id':2,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/7/2.jpg"
        },
        {
          'id':3,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/7/3.jpg"
        },
        {
          'id':4,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/7/4.jpg"
        },
        {
          'id':5,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/7/5.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/7/6.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/7/7.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/7/8.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/7/9.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/7/10.jpg"
        },

      ],
      'imageneight':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/8/1.jpg"
        },
        {
          'id':2,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/8/2.jpg"
        },
        {
          'id':3,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/8/3.jpg"
        },
        {
          'id':4,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/8/4.jpg"
        },
        {
          'id':5,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/8/5.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/8/6.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/8/7.jpg"
        },
      ],
      'imagennine':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/9/1.jpg"
        },
        {
          'id':2,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/9/2.jpg"
        },
        {
          'id':3,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/9/3.jpg"
        },
        {
          'id':4,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/9/4.jpg"
        },
        {
          'id':5,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/9/5.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/9/6.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/9/7.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/9/8.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/9/9.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/9/10.jpg"
        },

      ],
      'imagenten':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/10/1.jpg"
        },
        {
          'id':2,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/10/2.jpg"
        },
        {
          'id':3,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/10/3.jpg"
        },
        {
          'id':4,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/10/4.jpg"
        },
        {
          'id':5,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/10/5.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/10/6.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/10/7.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/10/8.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/10/9.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/10/10.jpg"
        },

      ],
      'imageneleven':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/11/1.jpg"
        },
        {
          'id':2,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/11/2.jpg"
        },
        {
          'id':3,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/11/3.jpg"
        },
        {
          'id':4,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/11/4.jpg"
        },
        {
          'id':5,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/11/5.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/11/6.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/11/7.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/11/8.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/11/9.jpg"
        },


      ],
      'imagentwelve':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/12/1.jpg"
        },
        {
          'id':2,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/12/2.jpg"
        },
        {
          'id':3,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/12/3.jpg"
        },
        {
          'id':4,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/12/4.jpg"
        },
        {
          'id':5,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/12/5.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/12/6.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/12/7.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/12/8.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/12/9.jpg"
        },


      ],
      'imagenthirteen':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/13/1.jpg"
        },
        {
          'id':2,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/13/2.jpg"
        },
        {
          'id':3,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/13/3.jpg"
        },
        {
          'id':4,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/13/4.jpg"
        },
        {
          'id':5,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/13/5.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/13/6.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/13/7.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/13/8.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/13/9.jpg"
        },

      ],
      'imagenfourteen':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/14/1.jpg"
        },
        {
          'id':2,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/14/2.jpg"
        },
        {
          'id':3,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/14/3.jpg"
        },
        {
          'id':4,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/14/4.jpg"
        },
        {
          'id':5,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/14/5.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/14/6.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/14/7.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/14/8.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/14/9.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/14/10.jpg"
        },

      ],
      'imagenfifteen':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/15/1.jpg"
        },
        {
          'id':2,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/15/2.jpg"
        },
        {
          'id':3,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/15/3.jpg"
        },
        {
          'id':4,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/15/4.jpg"
        },
        {
          'id':5,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/15/5.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/15/6.jpg"
        },
        {
          'id':6,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/15/7.jpg"
        },

      ],
      'imagensixteen':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/16/1.jpg"
        },
        {
          'id':2,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/16/2.jpg"
        },
        {
          'id':3,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/16/3.jpg"
        },
        {
          'id':4,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/two/16/4.jpg"
        }
      ],
    },
    {
      'id':3,
      'name':'Mantenimiento del sistema eléctrico de saunas unipersonales',
      'price':'',
      'breve': 'Realizamos mantenimiento de sistemas eléctricos como...',
      'buttontype':'solicitar',
      'tipo':'servicios',
      'linkbtn':"mantenimiento-saunas",
      'mensaje':'Hola buenas tardes deseo adquirir el servicio de Mantenimiento del sistemas eléctrico, cual es el prodecimiento...',
      'imagen':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/3/1.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/3/2.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/3/3.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/3/4.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/3/5.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/3/6.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/3/7.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/3/8.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/3/9.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/3/10.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/3/11.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/3/12.jpg"
        },
    
  

      ]
    },
    {
      'id':4,
      'name':'Fabricación de todo tipo de Piezas',
      'price':'',
      'breve': 'Fabricación de todo tipo de piezas, matrices o prototipos en fibra de vidrio',
      'buttontype':'solicitar',
      'tipo':'servicios',
      'linkbtn':"fabricación-piezas",
      'mensaje':'Hola%20buenas%20tardes%20deseo%20adquirir%20el%20servicio%20de%20Elaboraci%C3%B3n%20de%20tanques%20reservorios%2C%20cual%20es%20el%20prodecimiento...',
      'imagen':[
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/1.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/2.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/3.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/4.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/5.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/6.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/7.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/8.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/9.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/10.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/11.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/12.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/13.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/14.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/15.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/16.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/17.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/18.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/19.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/20.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/21.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/22.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/23.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/24.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/25.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/26.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/27.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/28.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/29.jpg"
        },
        {
          'id':1,
          "img":"https://apiweb.netlify.app/images/fibras/servicios/4/30.jpg"
        },
      ]
    },
  ],
  reparaciones: [
    {
        "id":1,
        "name":"Mantenimiento Jacuzzi",
        "place":"Jr. Marginal",
        "district":"San Borja",
        "modal" :"OpenModal",
        "number":""
    },
    {
        "id":2,
        "name":"Pintado de Tina de Baño",
        "place":"",
        "district":"Callao",
        "modal" :"two",
        "number":""
    },
    {
        "id":3,
        "name":"Pintado de Tina de hierro",
        "place":"",
        "district":"Centro de lima",
        "modal" :"three",
        "number":""
    },
    {
        "id":4,
        "name":"Reparación de Jacuzzi",
        "place":"Calle Brahm 139 dpto",
        "district":"San Borja",
        "modal" :"four",
        "number":""
    },
    {
        "id":5,
        "name":"Reparación de Jacuzzi de Playa",
        "place":"",
        "district":"Sur de lima",
        "modal" :"five",
        "number":""
    },
    {
        "id":6,
        "name":"Reparación de Jacuzzi",
        "place":"",
        "district":"La Molina",
        "modal" :"six",
        "number":""
    },
    {
        "id":7,
        "name":"Reparación de tina de baño",
        "place":"",
        "district":"Surco",
        "modal" :"",
        "number":""
    },
    {
        "id":8,
        "name":"Reparación de tina de baño esquinero",
        "place":"",
        "district":"Surco",
        "modal" :"",
        "number":""
    },
    {
        "id":9,
        "name":"Reparación de tina de baño",
        "place":"",
        "district":"Pachacamac",
        "modal" :"",
        "number":""
    },
    {
        "id":10,
        "name":"Reparación de tina de baño",
        "place":"",
        "district":"San Isidro",
        "modal" :"",
        "number":""
    },
    {
        "id":11,
        "name":"Reparacion de tina, desinstalacion e instalación",
        "place":"",
        "district":"Callao",
        "modal" :"",
        "number":""
    },
    {
        "id":12,
        "name":"Reparación de tina",
        "place":"",
        "district":"San Isidro",
        "modal" :"",
        "number":""
    },
    {
        "id":113,
        "name":"Reparación de tina",
        "place":"",
        "district":"San Isidro",
        "modal" :"",
        "number":""
    },
    {
      "id":14,
      "name":"Reparación de jacuzzi",
      "place":"Laguna Grnde",
      "district":"La Molina",
      "modal" :"",
      "number":""
    },
    {
      "id":15,
      "name":"Reparación de piscina",
      "place":"",
      "district":"San Isidro",
      "modal" :"",
      "number":""
    },
    {
      "id":16,
      "name":"Desinstalación e Instalación de tina de baño",
      "place":"",
      "district":"Cercado de Lima",
      "modal" :"",
      "number":""
    },
]
};